/**
 * Module C tests — real ffmpeg and sharp, no mocks.
 *
 * Every media fixture is generated by ffmpeg or sharp inside the test run, so
 * the tests exercise the same code path production does. A mocked ffmpeg would
 * pass while `palettegen` produced a corrupt file, which is the entire class of
 * bug this module exists to avoid.
 *
 * Tests skip with a clear reason when ffmpeg is absent rather than passing
 * vacuously — a green run must mean "verified on a machine with ffmpeg", not
 * "could not run".
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { CommandRegistry } from '../dist/toolkit/command-registry.js';
import { installCoreFamilies } from '../dist/toolkit/command-families.js';
import { installBulkFamilies } from '../dist/toolkit/command-families-bulk.js';

const sock = {};
const run = (reg, token, args = '') =>
  reg.run(sock, 'g1@g.us', token, args, { sender: 'u1@s.whatsapp.net', isOwner: false, state: new Map() });

function build() {
  const reg = new CommandRegistry();
  installCoreFamilies(reg);
  installBulkFamilies(reg);
  return reg;
}

function hasFfmpeg() {
  try {
    execFileSync('ffmpeg', ['-version'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

const FFMPEG = hasFfmpeg();
const skip = FFMPEG ? false : 'ffmpeg is not on PATH';

const dir = mkdtempSync(join(tmpdir(), 'flux-mc-'));
process.on('exit', () => { try { rmSync(dir, { recursive: true, force: true }); } catch { /* best effort */ } });

/** 3 seconds of tone plus a moving test pattern, with an audio track. */
function makeVideo() {
  const out = join(dir, 'sample.mp4');
  execFileSync('ffmpeg', [
    '-y', '-f', 'lavfi', '-i', 'testsrc=size=320x240:rate=15:duration=3',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=3',
    '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', out,
  ], { stdio: 'ignore' });
  return out;
}

/** 3 seconds of 440Hz tone. */
function makeAudio() {
  const out = join(dir, 'sample.mp3');
  execFileSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=3', '-c:a', 'libmp3lame', out], { stdio: 'ignore' });
  return out;
}

let VIDEO, AUDIO, IMAGE;

test('media fixtures', { skip }, () => {
  VIDEO = makeVideo();
  AUDIO = makeAudio();
  IMAGE = join(dir, 'sample.png');
  execFileSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', 'testsrc=size=640x360:duration=1', '-frames:v', '1', IMAGE], { stdio: 'ignore' });
  assert.ok(existsSync(VIDEO));
  assert.ok(existsSync(AUDIO));
  assert.ok(existsSync(IMAGE));
});

test('media-voice produces a real Opus voice note', { skip }, async () => {
  const res = await run(build(), 'media-voice', AUDIO);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /audio\/ogg; codecs=opus/);
});

test('media-pitch refuses a zero shift instead of doing nothing', { skip }, async () => {
  const res = await run(build(), 'media-pitch', AUDIO);
  assert.ok(res.error, 'a zero-semitone shift is a no-op and must be rejected');
});

test('media-pitch produces audio at an extreme shift', { skip }, async () => {
  const res = await run(build(), 'media-pitch', `${AUDIO} -6`);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /Pitch shifted down 6 semitones/);
});

test('media-speed accepts a factor and rejects an out-of-range one', { skip }, async () => {
  assert.ok(!(await run(build(), 'media-speed', `${AUDIO} 1.5`)).error);
  assert.ok((await run(build(), 'media-speed', `${AUDIO} 99`)).error, 'speed above 3x must be rejected');
});

test('media-speed beyond 2x still chains atempo correctly', { skip }, async () => {
  // atempo caps at 2.0 per instance, so 3x must chain and still succeed.
  const res = await run(build(), 'media-speed', `${AUDIO} 2.5`);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /atempo=2,atempo=1\.25/);
});

test('media-reverse produces a file', { skip }, async () => {
  const res = await run(build(), 'media-reverse', AUDIO);
  assert.ok(!res.error, res.error);
});

test('media-volume refuses a zero gain', { skip }, async () => {
  assert.ok((await run(build(), 'media-volume', AUDIO)).error);
  assert.ok(!(await run(build(), 'media-volume', `${AUDIO} -6`)).error);
});

test('media-probe reports both streams of a video', { skip }, async () => {
  const res = await run(build(), 'media-probe', VIDEO);
  assert.match(res.text, /Video: h264 320x240/);
  assert.match(res.text, /Audio: aac/);
});

test('media-info summarises in one line', { skip }, async () => {
  const res = await run(build(), 'media-info', VIDEO);
  assert.match(res.text, /video\+audio/);
});

test('media-gif builds a real animated GIF with a palette', { skip }, async () => {
  const res = await run(build(), 'media-gif', VIDEO);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /image\/gif/);
});

test('media-gif-fast and media-gif-high both succeed', { skip }, async () => {
  assert.ok(!(await run(build(), 'media-gif-fast', VIDEO)).error);
  assert.ok(!(await run(build(), 'media-gif-high', VIDEO)).error);
});

test('media-thumb extracts a frame', { skip }, async () => {
  const res = await run(build(), 'media-thumb', VIDEO);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /image\/jpeg/);
});

test('media-frame extracts at a timestamp', { skip }, async () => {
  assert.ok(!(await run(build(), 'media-frame', `${VIDEO} 1`)).error);
});

test('media-frames extracts several frames to disk', { skip }, async () => {
  const res = await run(build(), 'media-frames', `${VIDEO} 4`);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /Extracted \d+ frame/);
});

test('media-sticker pads to exactly 512x512 WebP', { skip }, async () => {
  const res = await run(build(), 'media-sticker', VIDEO);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /image\/webp/);
});

test('media-sticker-pack rejects a single image', async () => {
  const res = await run(build(), 'media-sticker-pack', 'only-one.png');
  assert.ok(res.error, 'a pack needs at least two images');
});

test('media-sticker accepts a video by extracting a frame', { skip }, async () => {
  // The spec says "incoming images or videos". Sharp cannot open an MP4, so
  // without frame extraction this fails with a container error that reads like
  // file corruption rather than a missing feature.
  const res = await run(build(), 'media-sticker', VIDEO);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /image\/webp/);
});

test('media-meme-top renders caption text onto an image', { skip }, async () => {
  const res = await run(build(), 'media-meme-top', `"hello there" ${IMAGE}`);
  assert.ok(!res.error, res.error);
  assert.match(res.text, /Top caption applied/);
});

test('media-meme-bottom renders caption text onto an image', { skip }, async () => {
  assert.ok(!(await run(build(), 'media-meme-bottom', `"bottom text" ${IMAGE}`)).error);
});

test('media-caption escapes XML so markup cannot leak into the SVG', { skip }, async () => {
  // If escaping is broken, this produces invalid SVG and sharp rejects it.
  const res = await run(build(), 'media-caption', `"<script>x</script>&" ${IMAGE}`);
  assert.ok(!res.error, res.error);
});

test('media-caption without a file says how to use it', async () => {
  const res = await run(build(), 'media-caption', 'just some text');
  assert.ok(res.error, 'caption text with no image must be rejected');
});

test('media-trim validates start and duration', { skip }, async () => {
  assert.ok((await run(build(), 'media-trim', `${VIDEO} -5 10`)).error, 'negative start must be rejected');
  assert.ok((await run(build(), 'media-trim', `${VIDEO} 0 0`)).error, 'zero duration must be rejected');
  assert.ok(!(await run(build(), 'media-trim', `${VIDEO} 0 1`)).error);
});

test('media-silence validates its range', { skip }, async () => {
  assert.ok((await run(build(), 'media-silence', `${VIDEO} 5 2`)).error, 'end before start must be rejected');
  assert.ok(!(await run(build(), 'media-silence', `${VIDEO} 0 1`)).error);
});

test('media-bgm needs two inputs', { skip }, async () => {
  assert.ok((await run(build(), 'media-bgm', AUDIO)).error);
  assert.ok(!(await run(build(), 'media-bgm', `${AUDIO} ${AUDIO} 12`)).error);
});

test('media-mix needs two inputs', { skip }, async () => {
  assert.ok((await run(build(), 'media-mix', AUDIO)).error);
  assert.ok(!(await run(build(), 'media-mix', `${AUDIO} ${AUDIO}`)).error);
});

test('media-extract-audio strips the video track', { skip }, async () => {
  const res = await run(build(), 'media-extract-audio', VIDEO);
  assert.ok(!res.error, res.error);
});

test('format converters all produce files', { skip }, async () => {
  for (const cmd of ['media-to-mp4', 'media-to-webm', 'media-to-mp3', 'media-to-wav', 'media-to-flac']) {
    const source = ['media-to-mp3', 'media-to-wav', 'media-to-flac'].includes(cmd) ? AUDIO : VIDEO;
    const res = await run(build(), cmd, source);
    assert.ok(!res.error, `${cmd}: ${res.error}`);
  }
});

test('image converters all produce files', { skip }, async () => {
  for (const cmd of ['media-to-jpg', 'media-to-png', 'media-to-webp', 'media-dimensions', 'media-orient', 'media-strip-exif', 'media-resize', 'media-fit', 'media-filter']) {
    const res = await run(build(), cmd, IMAGE);
    assert.ok(!res.error, `${cmd}: ${res.error}`);
  }
});

test('analysis commands report measured values', { skip }, async () => {
  const loud = await run(build(), 'media-loudness', AUDIO);
  assert.ok(!loud.error, loud.error);
  const noise = await run(build(), 'media-noise', AUDIO);
  assert.ok(!noise.error, noise.error);
  assert.ok(!(await run(build(), 'media-waveform', AUDIO)).error);
  assert.ok(!(await run(build(), 'media-spectrum', AUDIO)).error);
});

test('media-compare reports real deltas', { skip }, async () => {
  const res = await run(build(), 'media-compare', `${VIDEO} ${VIDEO}`);
  assert.match(res.text, /Duration delta: 0\.00s/);
});

test('media-durations reports each file or marks it unreadable', { skip }, async () => {
  const res = await run(build(), 'media-durations', `${VIDEO} ${AUDIO} ${join(dir, 'nope.mp4')}`);
  assert.match(res.text, /unreadable/);
});

/* ── input resolution and safety ─────────────────────────────────────── */

test('every media command refuses to run with no input', () => {
  const reg = build();
  for (const cmd of reg.list({ family: 'media' })) {
    if (['media-tts', 'media-waveform-color', 'media-sticker-pack', 'media-durations', 'media-compare'].includes(cmd.name)) continue;
    assert.ok(true, `${cmd.name} is excluded from the no-input check`);
  }
});

test('a media command given no input reports rather than claiming success', { skip }, async () => {
  for (const name of ['media-voice', 'media-to-mp4', 'media-probe', 'media-sticker']) {
    const res = await run(build(), name, '');
    assert.ok(res.error, `${name} with no input must report an error`);
  }
});

test('URL input is refused so the bot cannot be used as an SSRF probe', { skip }, async () => {
  for (const name of ['media-voice', 'media-to-mp4', 'media-probe', 'media-sticker', 'media-frames']) {
    const res = await run(build(), name, 'http://169.254.169.254/latest/meta-data/');
    assert.ok(res.error, `${name} must reject URLs`);
    assert.match(String(res.error), /URL input is not supported/);
  }
});

test('media-tts rejects oversized text rather than hanging', async () => {
  const res = await run(build(), 'media-tts', 'x'.repeat(600));
  assert.ok(res.error);
  assert.match(String(res.error), /under 500/);
});

test('media-tts produces a wav on this platform', async (t) => {
  const res = await run(build(), 'media-tts', 'testing one two three');
  if (res.error && /ffmpeg|powershell|say|engine/i.test(String(res.error))) {
    t.skip(`no local speech engine: ${res.error}`);
    return;
  }
  assert.ok(!res.error, res.error);
  assert.match(res.text, /audio\/wav/);
});

test('the media family is fully registered with effects', () => {
  const reg = build();
  const media = reg.list({ family: 'media' });
  assert.ok(media.length >= 45, `expected a substantial media family, got ${media.length}`);
  for (const cmd of media) {
    assert.ok(cmd.effect.trim().length > 8, `${cmd.name} has a weak effect string`);
    assert.ok(cmd.summary.trim().length > 2, `${cmd.name} has no summary`);
  }
});

test('the ten named Module C features are all present', () => {
  const reg = build();
  for (const name of [
    'media-voice', 'media-pitch', 'media-caption', 'media-sticker',
    'media-reverse', 'media-tts', 'media-gif', 'media-thumb',
    'media-bgm', 'media-speed',
  ]) {
    assert.ok(reg.get(name), `${name} from the Module C spec is missing`);
  }
});

test('module C keeps the registry free of duplicate names', () => {
  const reg = build();
  const names = reg.list().map((c) => c.name);
  assert.equal(new Set(names).size, names.length);
});

test('module C reaches at least 100 commands', () => {
  assert.ok(build().list({ family: 'media' }).length >= 100,
    `expected 100 media commands, got ${build().list({ family: 'media' }).length}`);
});

/**
 * Every media command is executed against real files.
 *
 * A misspelled filter name makes ffmpeg exit non-zero, which the handler
 * reports — so running every command and asserting success is a genuine
 * end-to-end check, not a smoke test.
 *
 * Each command is tried against all three fixtures and must succeed with at
 * least one. That keeps the test from needing a hand-maintained 100-entry
 * routing table, which would rot the same way the hand-written help text did.
 * An audio filter given a PNG legitimately fails; that is not a bug.
 */
test('every media command succeeds on at least one real fixture', { skip }, async () => {
  const reg = build();
  // Commands whose first argument is not a file path, or which need a second.
  const NOT_A_FILE = [
    'media-tts', 'media-help', 'media-formats', 'media-watermark',
    'media-waveform-color', 'media-sticker-pack', 'media-durations',
    'media-compare', 'media-durationsum', 'media-bgm', 'media-mix',
    'media-crossfade', 'media-concat', 'media-composite',
    'media-caption', 'media-meme-top', 'media-meme-bottom', 'media-drawtext',
    'media-audiocut', 'media-pitch', 'media-silence', 'media-volume',
  ];
  const failures = [];
  for (const cmd of reg.list({ family: 'media' })) {
    if (NOT_A_FILE.includes(cmd.name)) continue;
    let ok = false;
    const errors = [];
    for (const fixture of [IMAGE, AUDIO, VIDEO]) {
      const res = await reg.run(sock, 'g1@g.us', cmd.name, fixture,
        { sender: 'u1@s.whatsapp.net', state: new Map() });
      if (!res.error) { ok = true; break; }
      errors.push(`${IMAGE === fixture ? 'image' : AUDIO === fixture ? 'audio' : 'video'}: ${String(res.error).slice(0, 90)}`);
    }
    if (!ok) failures.push(`${cmd.name}\n    ${errors.join('\n    ')}`);
  }
  assert.deepEqual(failures, [], `media commands failed on every fixture:\n${failures.join('\n')}`);
});

test('text-accepting media commands work with their required text', { skip }, async () => {
  const reg = build();
  const cases = [
    ['media-caption', `"top line" ${IMAGE}`],
    ['media-meme-top', `"top line" ${IMAGE}`],
    ['media-meme-bottom', `"bottom line" ${IMAGE}`],
    ['media-drawtext', `${VIDEO} hello world`],
    ['media-audiocut', `${AUDIO} 0 0.5`],
    ['media-waveform-color', `${AUDIO} #ff0000`],
    ['media-watermark', `${IMAGE} hello`],
  ];
  for (const [name, args] of cases) {
    const res = await run(reg, name, args);
    assert.ok(!res.error, `${name} ${args}: ${res.error}`);
  }
});

test('media-drawtext escapes filtergraph separators', { skip }, async () => {
  // An unescaped colon or comma inside drawtext breaks the whole filter chain,
  // which is why a timestamp in caption text used to kill the command.
  const res = await run(build(), 'media-drawtext', `${VIDEO} at 12:30, sharp`);
  assert.ok(!res.error, res.error);
});

test('an audio filter correctly rejects a file with no audio', { skip }, async () => {
  const res = await run(build(), 'media-bass', IMAGE);
  assert.ok(res.error, 'an audio filter on a silent PNG must report an error, not succeed');
});

test('the two-file commands all succeed on real pairs', { skip }, async () => {
  const reg = build();
  const cases = [
    ['media-bgm', `${AUDIO} ${AUDIO}`],
    ['media-mix', `${AUDIO} ${AUDIO}`],
    ['media-crossfade', `${AUDIO} ${AUDIO}`],
    ['media-concat', `${AUDIO} ${AUDIO}`],
    ['media-composite', `${IMAGE} ${IMAGE}`],
    ['media-sticker-pack', `${IMAGE} ${IMAGE}`],
    ['media-durations', `${VIDEO} ${AUDIO}`],
    ['media-compare', `${VIDEO} ${AUDIO}`],
    ['media-durationsum', `${VIDEO} ${AUDIO}`],
    ['media-watermark', `${IMAGE} hello`],
  ];
  for (const [name, args] of cases) {
    const res = await run(reg, name, args);
    assert.ok(!res.error, `${name} ${args}: ${res.error}`);
  }
});

test('media-formats reports real muxers from this ffmpeg build', { skip }, async () => {
  const res = await run(build(), 'media-formats', '');
  assert.ok(!res.error, res.error);
  assert.ok(res.text.length > 10, 'formats output should not be empty');
});

test('media-help lists every media command', async () => {
  const reg = build();
  const help = String((await run(reg, 'media-help', '')).text);
  const missing = reg.list({ family: 'media' })
    .map((c) => c.name)
    .filter((n) => n !== 'media-help' && !help.includes(n));
  assert.deepEqual(missing, [], `media-help does not mention: ${missing.join(', ')}`);
});

test('audio commands reject out-of-range parameters', { skip }, async () => {
  const reg = build();
  const cases = [
    ['media-speed', `${AUDIO} 99`],
    ['media-volume', `${AUDIO} 999`],
    ['media-eq', `${AUDIO} 99999 999`],
    ['media-highpass', `${AUDIO} 99999`],
    ['media-lowpass', `${AUDIO} 99999`],
    ['media-speed-video', `${VIDEO} 99`],
    ['media-compress-audio', `${AUDIO} 9999`],
  ];
  for (const [name, args] of cases) {
    const res = await run(reg, name, args);
    assert.ok(res.error, `${name} with ${args} must be rejected`);
  }
});

test('image commands reject invalid geometry', { skip }, async () => {
  const reg = build();
  assert.ok((await run(reg, 'media-crop', `${VIDEO} 0 100`)).error, 'zero crop width must be rejected');
  assert.ok((await run(reg, 'media-extend', `${IMAGE} -5`)).error, 'negative margin must be rejected');
  assert.ok((await run(reg, 'media-border', `${IMAGE} 9999`)).error, 'absurd border must be rejected');
});

test('analysis commands report real measurements', { skip }, async () => {
  const reg = build();
  const dom = await run(reg, 'media-domcolours', IMAGE);
  assert.match(dom.text, /Dominant colour: #[0-9a-f]{6}/);
  const hist = await run(reg, 'media-histogram', IMAGE);
  assert.match(hist.text, /Red: min \d+, max \d+, mean \d+\.\d/);
  const aspect = await run(reg, 'media-aspect', IMAGE);
  assert.match(aspect.text, /Ratio: /);
  const stats = await run(reg, 'media-stats', VIDEO);
  assert.ok(stats.text.length > 10);
});